apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-bhkv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-bhkv
    app.kubernetes.io/part-of: test-app-bmfx
  name: test-component-bhkv
  namespace: build-e2e-qhpd-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-bhkv
    weight: 100
status: {}
